
SAGA_SUBDIRS = core packages

SAGA_HDR     = $(wildcard *.hpp)
SAGA_SRC     = $(wildcard *.cpp)
SAGA_LIB_OBJ = $(SAGA_SRC:%.cpp=%.o)
SAGA_LIB     = saga

SAGA_ROOT    = $(shell pwd)/../../

include $(SAGA_ROOT)/make/saga.mk

