
SAGA_HDR         = $(wildcard *.hpp)

SAGA_ROOT        = $(shell pwd)/../..
SAGA_BIN         = test_shared_ptr

# SAGA_ARC         = saga_util
# SAGA_LIB_OBJ     = demangle.o

include $(SAGA_ROOT)/make/saga.application.mk

