
SAGA_HDR     = $(wildcard *.hpp)
SAGA_SRC     = $(wildcard *.cpp)
SAGA_LIB_OBJ = $(SAGA_SRC:%.cpp=%.o)
SAGA_LIB     = saga_cpi_core

SAGA_ROOT    = $(shell pwd)/../../..

include $(SAGA_ROOT)/make/saga.mk

