
SAGA_HDR     = $(wildcard *.hpp)

SAGA_ROOT    = $(shell pwd)/../../../

SAGA_BIN    += doc_pimple_shared_pointer
SAGA_BIN    += doc_pimple_multiple_inheritance

include $(SAGA_ROOT)/make/saga.application.mk

